<?php

namespace Database\Seeders;

use App\Models\Calendar;
use Illuminate\Database\Seeder;
use function now;

class CalendarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Calendar::insert([
            [
                'giorno' => '1',
                'orario' => '10:30',
                'course_id' => 3,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '1',
                'orario' => '11:00',
                'course_id' => 3,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '1',
                'orario' => '13:30',
                'course_id' => 4,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '1',
                'orario' => '14:00',
                'course_id' => 4,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '2',
                'orario' => '19:30',
                'course_id' => 4,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '2',
                'orario' => '20:00',
                'course_id' => 4,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '1',
                'orario' => '18:30',
                'course_id' => 5,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '1',
                'orario' => '19:00',
                'course_id' => 5,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '2',
                'orario' => '13:30',
                'course_id' => 5,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '2',
                'orario' => '14:00',
                'course_id' => 5,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '3',
                'orario' => '19:30',
                'course_id' => 22,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '3',
                'orario' => '20:00',
                'course_id' => 22,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '1',
                'orario' => '19:30',
                'course_id' => 6,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '1',
                'orario' => '20:00',
                'course_id' => 6,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '3',
                'orario' => '19:30',
                'course_id' => 6,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '3',
                'orario' => '20:00',
                'course_id' => 6,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '5',
                'orario' => '18:00',
                'course_id' => 6,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '5',
                'orario' => '18:30',
                'course_id' => 6,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '1',
                'orario' => '19:30',
                'course_id' => 7,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '1',
                'orario' => '20:00',
                'course_id' => 7,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '2',
                'orario' => '10:00',
                'course_id' => 8,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '2',
                'orario' => '10:30',
                'course_id' => 8,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '2',
                'orario' => '18:00',
                'course_id' => 9,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '2',
                'orario' => '18:30',
                'course_id' => 9,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '2',
                'orario' => '20:30',
                'course_id' => 10,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '2',
                'orario' => '21:00',
                'course_id' => 10,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '3',
                'orario' => '13:30',
                'course_id' => 11,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '3',
                'orario' => '14:00',
                'course_id' => 11,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '4',
                'orario' => '18:00',
                'course_id' => 21,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '4',
                'orario' => '18:30',
                'course_id' => 21,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '4',
                'orario' => '20:30',
                'course_id' => 10,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '4',
                'orario' => '21:00',
                'course_id' => 10,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '2',
                'orario' => '20:30',
                'course_id' => 2,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '2',
                'orario' => '21:00',
                'course_id' => 2,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '3',
                'orario' => '09:00',
                'course_id' => 17,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '3',
                'orario' => '09:30',
                'course_id' => 17,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '5',
                'orario' => '19:00',
                'course_id' => 1,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '5',
                'orario' => '19:30',
                'course_id' => 1,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '3',
                'orario' => '18:00',
                'course_id' => 1,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '3',
                'orario' => '18:30',
                'course_id' => 1,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '3',
                'orario' => '18:00',
                'course_id' => 11,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '3',
                'orario' => '18:30',
                'course_id' => 11,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '3',
                'orario' => '18:30',
                'course_id' => 12,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '3',
                'orario' => '19:00',
                'course_id' => 12,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '4',
                'orario' => '19:00',
                'course_id' => 12,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '4',
                'orario' => '19:30',
                'course_id' => 12,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '5',
                'orario' => '13:30',
                'course_id' => 12,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '5',
                'orario' => '14:00',
                'course_id' => 12,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '4',
                'orario' => '13:30',
                'course_id' => 13,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '4',
                'orario' => '14:00',
                'course_id' => 13,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '4',
                'orario' => '19:30',
                'course_id' => 13,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '4',
                'orario' => '20:00',
                'course_id' => 13,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '4',
                'orario' => '18:00',
                'course_id' => 23,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '4',
                'orario' => '18:30',
                'course_id' => 23,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '4',
                'orario' => '21:00',
                'course_id' => 14,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '4',
                'orario' => '21:30',
                'course_id' => 14,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '5',
                'orario' => '18:00',
                'course_id' => 15,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '5',
                'orario' => '18:30',
                'course_id' => 15,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '1',
                'orario' => '09:00',
                'course_id' => 8,
                'mezza' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'giorno' => '1',
                'orario' => '09:30',
                'course_id' => 8,
                'mezza' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
